name: Deploy to staging
on:
  workflow_run:
    workflows:
      - "Backend"
      - "Frontend"
    types:
      - completed
    branches: [next]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: backend.yml
          workflow_conclusion: success
          branch: next
          name: build
          path: ${{ github.workspace }}/release_backend

      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: frontend.yml
          workflow_conclusion: success
          branch: next
          name: assets
          path: ${{ github.workspace }}/release_frontend

      - run: tree $GITHUB_WORKSPACE
      - run: diff $GITHUB_WORKSPACE/release_backend/github_sha.txt $GITHUB_WORKSPACE/release_frontend/github_sha.txt
