name: Deploy to staging
on:
  workflow_run:
    workflows:
      - "Backend"
      - "Frontend"
    types:
      - completed
    branches: [next]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: Backend
          workflow_conclusion: success
          branch: next
          name: build
          path: $GITHUB_WORKSPACE

      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: Backend
          workflow_conclusion: success
          branch: next
          name: assets
          path: $GITHUB_WORKSPACE

      - run: tree
